---
name: Lint

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v3

      - name: Use Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with: { bun-version: latest }

      - name: Cache NPM packages
        uses: actions/cache@v4
        env: { cache-name: npm }
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install NPM packages
        run: bun install --frozen-lockfile

      - name: Lint code
        run: bun run lint
